sudo: false
language: java
dist: trusty
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    repo: igniterealtime/openfire-threaddump-plugin
    all_branches: true
env:
  global:
  - secure: OHbMdbVRaZJRCTUpNOtzhtx/eZ7XLcR/9ZNW5ho0u8Cn9ybczDPU6xoALgk/a6KoBCx3B6ErV+mz9nd4tJ14v7+t/jix0h5xzFtl8XNoRbnyJ31JfTU62bob6XtWh6wX8+tBwBWX0TJ+aGd7q3nY8n58cW9G2y+K/f0nkKtb+sErnfQ9A98iFjj5KW1Y9BLRk9dPGaoqc7dV5ri/U6qD8jCX9jikX+Y1Qg/YJMJ4Qna7/8siJyMHM2TMUXCvwWHjZrLh/NmMVr3RtzU5bLqnGUvxmzndzK9Ff3xLq8Rg+CI+T0J7XFDNEScpYROkQikyDnS4QogJS7oh3fFye4n6l40naQ9zIowqPl+Wn3vARAZKLRjZvBXMwx2oWZz+waVuWjTDbZm6yFymwScMkiTh9UdfbLhPb9BBGhIAURD1X1xZiv5c6WqOqyFHmd3tByfsS6+6dKnYm6/BqJn/y1vq8nzLzsb4sRLS2xQe7q5kceTOh6qmFMuPKP8KqvPwpdJhq4AlUWUJkNcZj7YlyWPDqhnavi3V1SVYm9ClbFZiob8EkXkfgn7PaZuKDtiCjVqzrTj0hVwoC3EXh85gMXd1nBaIJ16xoYEjvMZUF6WAj5G7UWNL4kHzFEXjuRtKi05oKmEqCCtGAFGslH46DJEfI9+s6XasQSrZnBq46LhobUU=
  - secure: rGTDs8nKyJI4cJMmyPpPVawskWTjswFRFHBo26Rm90Pk4aZQetYa/yRcYV4wGEKXzT7Qa+lHY2Cbxp9B9aiklz6etgy3uetf9YdiWU70s8g5lMzyXaQ5tkrteHvSsbt187YUw5LWNz8xMf9ZNdYtVMVKgKj50fqq496hXecrc9JwA0e+XslaEGEzlPlfOJWEUr6sWiEe2O5PL0o1CYzscpI+QZZR1f7qtMhQ3gteRc1kF/3Rz8j+l7EmiV64pLl5V8j1J/DXly38FDC8EXHaugmzDHkRe0kVpfNDSY/GM9+Lt3MPl+dJhniGQqdQ5eRsWIJjueuhUFqe/knSwAyh9Al6rUN9JBd0xK08d03Rw85dwWTMOuodA/puZ4VsgABfcrhYP6xfNkqG+3sbDqmNC3Jsc8BIASS5MCLmAwkqcKsmbUlfysrBwztwL6m9X/WHhnT8d7MFMxBlOVecHOtHxzm1AT3+iVayn+oh6d3taWUmLFEquC7JVvJoU2DQc2R8WJMDMmlRdHatQQ6/QF5Gdc6wrkCM3VLN8fwHTfYC7vhluosyIGkn7Edg5je6LBE08kK/RWCB73iIZvhJPfOgCafWncQUdXmoTVRhiBTBOKxNoUFcZYk/H/iGQ3mg4tK6RmBG1Kfo0myT9ZW2FbxDGgdZIsfxyhFvDl6C1KaDsfk=
